### ISSUE TITLE
_tkinter.TclError: wrong # args: should be "wm iconbitmap window ?bitmap?"

### ISSUE THREAD

**Issue by Ao1ia0** [kracer127/SeBruteGUI#1]
Traceback (most recent call last):
  File "SeBruteGUI.py", line 476, in <module>
    GUI().run()
  File "SeBruteGUI.py", line 24, in __init__
    self.root.iconbitmap(default=r'.//imgs//icon.ico')
  File "/Library/Developer/CommandLineTools/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/tkinter/__init__.py", line 2078, in wm_iconbitmap
    return self.tk.call('wm', 'iconbitmap', self._w, '-default', default)
_tkinter.TclError: wrong # args: should be "wm iconbitmap window ?bitmap?"

**Comment by kracer127** [comment]
直接把图标代码去掉吧，mac的图片格式问题应该是

**Comment by Ao1ia0** [comment]
注释掉是可以运行了，但是运行后整个界面是一闪一闪的
![image](https://user-images.githubusercontent.com/71432693/142962976-5e1cd3cf-a4f8-4a96-8ee8-9943545986d8.png)

**Comment by kracer127** [comment]
好的，后续mac系统的我会优化
